site_name: Fair Meeting Planner
theme:
  name: material
nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Cookbook: cookbook.md
  - API Reference: api.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: yes
